In [2]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print("A: \n", A)
# SVD
U, s, VT = svd(A)
print("\nU: \n", U)
print("\ns: \n", s)
print("\nV^T: \n", VT)

A: 
 [[1 2]
 [3 4]
 [5 6]]

U: 
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

s: 
 [9.52551809 0.51430058]

V^T: 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
