In [1]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print("type: " ,type(a))            # Prints "<class 'numpy.ndarray'>"
print("shape: " ,a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print("\n shape of b:",b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

a = np.zeros((3,3))   # Create an array of all zeros
print("All zeros matrix:\n  " ,a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print("\nAll ones matrix:\n  " ,b)              # Prints "[[ 1.  1.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print("\n identity matrix: \n",d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print("\n random matrix: \n",e)

type:  <class 'numpy.ndarray'>
shape:  (3,)
1 2 3
[5 2 3]

 shape of b: (2, 3)
1 2 4
All zeros matrix:
   [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

All ones matrix:
   [[1. 1.]]

 identity matrix: 
 [[1. 0.]
 [0. 1.]]

 random matrix: 
 [[0.50738093 0.49587583]
 [0.85821263 0.69582347]]
